### ISSUE TITLE
[rush] Overriding `rush rebuild` command

### ISSUE THREAD

**Issue by ScottHysom** [Microsoft/web-build-tools#1020]
Our team would like to normalize the build command idioms:
- **Build** - perform a build, which may be an incremental build. Therefore, no clean step first.
- **Rebuild** - first clean, then "build"

These idioms follow the VS IDE "build" and "rebuild" commands. And it seems to be compatible with the purpose of the `rush rebuild` command today.

For engineers, their command pattern in a *package folder* would be:

```bash
# Just build and do the right thing
~/repo/packages/foo-pkg> npm run build

# I really want to do a clean build
~/repo/packages/foo-pkg> npm run rebuild
```

(In the corresponding package folder, the `package.json` `scripts` would specify both `build` and `rebuild` script commands.)

We would also like symmetrical commands when they use Rush.

```bash
# Build the whole repo and do the right thing. Behind the scenes, this spawns `npm run build` for each package.
~/repo> rush build

# Force a full clean build
~/repo> rush rebuild
```

This is where Rush breaks down for us. Today, Rush hardcodes the `build` and `rebuild` commands to `npm run build`. And we cannot override the `rebuild` command in `command-line.json` to cause it to spawn a different command other than `npm run build`.

Further, it appears that there is no additional parameter or environment variable passed to the npm build script to indicate whether a rebuild vs. build was invoked by the user via Rush. So our implementation of the `npm run build` command cannot infer anything from this.

Our only "work-around" solution today is to introduce a command-line parameter like `--clean`:

```bash
# Just build and do the right thing
~/repo/packages/foo-pkg> npm run build

# I really want to do a clean build
~/repo/packages/foo-pkg> npm run build --clean
```

and

```bash
# Build the whole repo and do the right thing.
~/repo> rush build

# Force a full clean build
~/repo> rush build --clean
```

But with this work-around, the "rebuild" definition is limited in scope to a Rush-only idiom, and you have these additional permutations of commands that adds to the complexity of choices for engineers:

```bash
# New engineer: "When should I use these different commands?"
~/repo> rush build

~/repo> rush build --clean

~/repo> rush rebuild

~/repo> rush rebuild --clean

# And the following are not functionally equivalent :(

# This will clean and build
~/repo/packages/foo-pkg> npm run rebuild

# This will *not* clean and build
~/repo/packages/foo-pkg> rush rebuild
```

# Proposed solutions
Here are some potential approaches to solving this problem:
1. Allow for `rebuild` command to be defined in the `command-line.json`. In the absence of this definition, default to today's `npm run build`.
2. Indicate to the `npm run build` script either through a new parameter or environment variable the context of whether the script was invoked via `rush build` vs. `rush rebuild`.

I personally favor proposal #1.

Thoughts?

**Comment by pgonzal** [comment]
BTW I've also always wanted to have a `rush clean` that simply cleans out your repo folders without building anything.

**Comment by pgonzal** [comment]
I agree with this proposal.  Historically we used to have separate scripts for "build" and "clean", and Rush would invoke them one after the other.  But due to limitations of gulp, this turned out be less efficient than packaging them together into a single `build --clean`.

Would you want to try your hand at creating a PR to implement #1?

**Comment by pgonzal** [comment]
Actually, hold on a sec...

There are two different concepts at play here.

Within a project:
- `npm run build --clean`: Deleting the previous output, and then rebuilding the entire project, VERSUS
- `npm run build`: Incrementally building the project, possibly reusing some outputs from the previous build (which sometimes can fail, e.g. if a naive glob finds some deadwood files in the output folder)

Across the monorepo:
- `rush rebuild`: Building all projects in the set, VERSUS
- `rush build`: Building only those projects whose Git-controlled source files have been touched since the previous successful build

Visual Studio's MSBuild does not really need the second concept, because it's a fast statically compiled engine, and its incremental build is aware of the universe of projects.

Whereas a JavaScript monorepo can use wildly different toolchains for each project, so we need to spin up separate **node.exe** instances to build each project.  And NodeJS is a slow interpreted language with thousands of files in the node_modules folder, so each **node.exe** invocation can cost several seconds of overhead.  The magic of `rush build` is that it can skip `npm run build` entirely, by performing its own analysis of the file timestamps in Rush's own **node.exe** instance.

Does that make sense?  So... perhaps Rush does need a few more knobs than Visual Studio.  But I agree the current design/naming is somewhat confusing.  Given those details, what do you think we should do? :-)

**Comment by pgonzal** [comment]
@kenotron who I heard has been thinking about toolchains and Rush lately

**Comment by ScottHysom** [comment]
Sorry, I didn't mean to confuse things by implying an incremental build engine like MSBuild.

Consider this: can `rush build` retain its existing purpose and design while still allowing `rush rebuild` to optionally invoke the packages' `rebuild` scripts vs. `build` scripts? 

I'm thinking it could look something like this:

1. `rush build` retains existing "is package dirty" algorithm to avoid invoking all packages' `npm run build` scripts if it determines some packages haven't changed. If a package has changed, Rush invokes the respective package's `npm run build`. 
    - This proposal would not change the `rush build` logic.

2. `rush rebuild` skips the "is package dirty" algorithm.
    - Today: it always invokes each package's `npm run build` script.
    - Proposal: it always invokes each package's `npm run build` **or** `npm run rebuild` script using this logic:
      - If `rebuild` is provided as a "bulk command" in `command-line.json`, then Rush will invoke `npm run rebuild` and it is incumbent on each package in the repo to support the `rebuild` script command.
      - If `rebuild` is not specified as a "bulk command", Rush falls back to invoking `npm run build` 

Would this still align with the intention of Rush's build vs. rebuild commands?

**Comment by ScottHysom** [comment]
Alternatively, instead of using `command-line.json` as a hint to Rush that we want a different script to be called in the rebuild vs. build commands, we could go a completely different route with option 2, and follow the pattern established by the [current lifecycle event in npm-scripts](https://docs.npmjs.com/misc/scripts#current-lifecycle-event).

I have submitted a new proposal to track option 2: #1023. I think the proposal for that issue actually has a bigger impact in that it can also help any command script that can be invoked by Rush to distinguish between being invoked by Rush vs. npm directly.
