### ISSUE TITLE
[rush] Allow customizing the commit message rush uses during publish

### ISSUE THREAD

**Issue by raygesualdo** [Microsoft/web-build-tools#1030]
**Current Behavior**
Commits from Rush during `rush publish` use the string "Applying package updates." and it cannot be changed. This causes our CI system to pick up the commit and try to run another CI build.

**Desired Behavior**
The string Rush uses when committing during `rush publish` is customizable so we can add the required by our CI system to skip CI builds.

**Prior Art**
[The `command.publish.message` config option for Lerna](https://github.com/lerna/lerna#lernajson).

**Comment by pgonzal** [comment]
@raygesualdo 

This seems like a useful feature.  Instead of calling the feature `gitPolicy.defaultCommitMessage`, would it be more clear to call it `gitPolicy.versionBumpCommitMessage`? Although today version bumping is pretty much the only operation where Rush creates Git commits, this is likely to change in the future.  

BTW is the `[skip-ci]` tag a standard recognized by many systems?  If not maybe we should exclude it from the default settings.

(BTW I was curious why we didn't encounter this issue in our own monorepos.  I think the difference is that our CI only runs for pull request branches, whereas `rush publish` pushes directly to the master branch.  Also we always publish on an schedule (hourly, daily), rather than publishing immediately after each commit.)

**Comment by raygesualdo** [comment]
Hey @pgonzal, thanks for the feedback! 

1. I'll rename it to `gitPolicy.versionBumpCommitMessage`. I'll also change the `rush.schema.json` file to include updated documentation: "The commit message Rush uses when commiting package version bumps."

   One additional question about the above change. It seems that a commit is happening in [`PublishActions.ts`](https://github.com/Microsoft/web-build-tools/pull/1031/files#diff-cdfcb9cb36a08402847687458a1ae501) as well. Would this configuration not apply to that commit? Currently, my PR does apply this configuration setting to that commit.

2. `[skip-ci]` was the wrong syntax. It should be `[skip ci]` and I'll update it. From my research, at least the following CI providers respect this syntax:

   - [CodeShip](https://documentation.codeship.com/general/projects/skipping-builds/#skipping-via-commit-message)
   - [CircleCI](https://circleci.com/docs/2.0/skip-build/#skipping-a-build)
   - [TravisCI](https://docs.travis-ci.com/user/customizing-the-build#skipping-a-build)
   - [AppVeyor](https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message)
   - [GitLab](https://docs.gitlab.com/ee/ci/yaml/#skipping-jobs)
   - [Bitbucket](https://confluence.atlassian.com/bitbucket/bitbucket-pipelines-faq-827104769.html#BitbucketPipelinesFAQ-CanIcommitwithouttriggeringthepipeline?)

   Based on this, thoughts on keeping it?

3. I think your intuitions are correct as to why you've never run into this before. Our release process commits/pushes straight to master, which would cause a CI loop without the skip directive.
