### ISSUE TITLE
[api-extractor] "export { }" emitted at the bottom of the .d.ts rollup file

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/web-build-tools#1049]
When using dtsRollup an extra unused `export { }` is emitted at the end of file.

I'd expect that such export is not present.

version: 7.0.11

**Comment by pgonzal** [comment]
This is by design actually. It is a workaround for a problem where TypeScript sometimes considers every declaration in a **.d.ts** file to be implicitly exported.  For example, (if I'm remembering right) you might have something like this:

**index.d.ts**
```ts
export declare class A { 
  x: number;
}
declare class B extends A { 
  y: number;
}
```

But then we found that the compiler would allow people to import both `B` and `A`, even though `B` wasn't actually exported by the Webpack bundle.  Appending `export {  }` to the bottom of the **.d.ts** file makes it so that `B` is no longer importable. 

I think @DanielRosenwasser explained that this syntax was a hack intended to avoid breaking compatibility with older typings, but I don't remember the details or justification.
