### ISSUE TITLE
[api-extractor] Doesn't seem to support exported React function components

### ISSUE THREAD

**Issue by craigkovatch** [Microsoft/web-build-tools#1076]
`utils/FocusTrap.tsx`:
```
import * as React from 'react';

function handleFocus(e: React.FocusEvent<HTMLElement>): void {
  e.stopPropagation();
}

function handleBlur(e: React.FocusEvent<HTMLElement>): void {
  const relatedTarget = (e.relatedTarget || document.activeElement) as HTMLElement;
  if (relatedTarget && !e.currentTarget.contains(relatedTarget)) {
    (e.target as HTMLElement).focus();
    e.stopPropagation();
  }
}

/** @internal */
export const FocusTrap: React.SFC = (props) => <div onBlur={handleBlur} onFocus={handleFocus}>{props.children}</div>;
```

Top-level entry point file:
```
export { FocusTrap } from './utils/FocusTrap';
```

Output from API extractor in `.api.ts`:
```
// WARNING: Unsupported export: FocusTrap
```

**Comment by octogonz** [comment]
Does this issue repro in the current API Extractor 7 beta?

To install the beta, try this:

```
npm install -g @microsoft/api-extractor@beta
```

The beta releases have version numbers like "7.0.5", but our [NPM disttag](https://www.npmjs.com/package/@microsoft/api-extractor?activeTab=versions) prevents them from getting installed as the "latest" version if you simply run `npm install -g @microsoft/api-extractor`.  We will update the disttag as soon as version 7 is stable.

**Comment by craigkovatch** [comment]
Looks like v7.0.11 works for this. Thanks for the tip. Is there somewhere I can easily see what's "coming soon" in v7?

**Comment by octogonz** [comment]
The minor changes are already published in the change log:

https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/CHANGELOG.md

The big changes are not well documented yet because I was waiting for the non-beta release, but it has taken way longer than expected. The gist is that in AE6 the .d.ts rollups used a new analysis engine that can handle a much wider variety of TypeScript constructs, and in AE7 everything now uses that engine. This revealed a ton of special cases in projects that do not use .d.ts rollups which has required a bunch of new tech to handle. Our main ship criteria for releasing the "beta" tag is to get the **office-ui-fabric-react** repo building with AE7. It's very close. My PR https://github.com/Microsoft/web-build-tools/pull/1077 is hopefully the last big fix (but you never know heheh). There are some other loose ends like reenabling warnings for missing exports, but they will be easy fixes and should go fast.

**Comment by octogonz** [comment]
Oh yeah, also the .api.json file format is different in AE7, and we now provide a full TypeScript API for loading/saving it. People who write doc generators should no longer need to work with this file format directly.

**Comment by craigkovatch** [comment]
@octogonz thank you for being so helpful and responsive! What are the instructions for pulling down #1077 and building locally? The build task I see in API Extractor's `package.json` seems to only run tests.

**Comment by octogonz** [comment]
Was this helpful? https://github.com/Microsoft/web-build-tools/issues/1054#issuecomment-460696228

**Comment by octogonz** [comment]
Closing since you said this was fixed in the AE7 beta. If not, please reopen this issue. Thanks!
