### ISSUE TITLE
[api-extractor] Enums don't seem to work correctly in API Extractor rollups.

### ISSUE THREAD

**Issue by iclanton** [Microsoft/web-build-tools#1105]
I just noticed an issue with the rolled up typings for `@microsoft/node-core-library`. The `Encoding` const enum isn't available to consumers of the library.

See this repro: https://github.com/Microsoft/web-build-tools/pull/1104

**Comment by octogonz** [comment]
The `Encoding` enum is a forgotten export.  It does appear in **rollup.d.ts**:

```ts
declare const enum Encoding {
    Utf8 = "utf8"
}
```

But you can't import it because the declaration doesn't have an `export` keyword.  The rollup is correct, since `Encoding` is not actually exported from **index.ts**.

However, we really need to reintroduce the missing exports warning in AE7.  I'm going to try to do that this weekend.

**Comment by iclanton** [comment]
Fixed here: https://github.com/Microsoft/web-build-tools/pull/1118

**Comment by octogonz** [comment]
> However, we really need to reintroduce the missing exports warning in AE7. I'm going to try to do that this weekend.

BTW this is fixed in [PR 1126](https://github.com/Microsoft/web-build-tools/pull/1126).
