### ISSUE TITLE
[api-extractor] What is the recommended way to deal with third-party types in review files

### ISSUE THREAD

**Issue by acchou** [Microsoft/web-build-tools#1114]
First of all thanks for all the work on api-extractor, it's a great project!

I have an API that has a few functions that take types from the AWS SDK and passes them through to the underlying API. For example:

```typescript
// @public (undocumented)
interface AwsOptions extends CommonOptions {
    // (undocumented)
    awsLambdaOptions?: Partial<aws.Lambda.Types.CreateFunctionRequest>;
}
```

The idea is to allow users to pass through advanced options to the underlying AWS lambda API. The only issue is that the generated api file doesn't type check because these external types are missing. Is there some way to have the api file import external apis, for example:

```typescript
import * as aws from "aws-sdk";
```

The idea is to leverage the type checker to help identify types that are missing accidentally, instead of relying on manual review of the api file alone. This can be accomplished by maintaining the invariant that the api file can be compiled without errors. Not sure this is a design goal for the api file but it seemed to be a natural way to use it to me.

I'm using AE8 through npm.

**Comment by octogonz** [comment]
When you say "API file" do you mean API review file (*.api.ts) or .d.ts rollup file (*.d.ts)? If the d.ts rollup is missing the import for a referenced declararion, that would be a bug.

> I'm using AE8 through npm.

FYI version 8.0.0 was published accidentally due to an incorrect config file, and NPM won't allow us to unpublish it after 72 hrs. The latest is actually 7.0.19.

**Comment by acchou** [comment]
I mean the API review file. Thanks for the tip on the version.

**Comment by octogonz** [comment]
The API review file is not intended to be valid TypeScript code.  It uses the ".ts" file extension for syntax coloring, however VS Code is generally expected to show red underlines indicating the semantic errors in this file.  I don't believe it its possible to make the file syntactically valid without compromising its purpose of avoiding diffs except when a signature changes.  I suppose we could change the file extension to something else like ".tsapi", but then we would want to define basic syntax coloring for that file extension.

There have been requests for this file to report on external libraries that are referenced.  However we would probably implement it as a simple list of package names, since if we use `import` statements we would have to deal with multiple denormalized forms of them.

**Comment by acchou** [comment]
Makes sense. Closing this issue.
