### ISSUE TITLE
[rush] Release Rush updates to npmjs.com more frequently

### ISSUE THREAD

**Issue by ScottHysom** [Microsoft/web-build-tools#1146]
Is there a publish cadence (to npmjs.com) that the web-build-tools repo aspires to meet? Also, is there a nightly or dev build vs. stable build concept? 

It would be super helpful if the changes that are merged into the repo become available more frequently. I am still seeing the last release on npmjs.com is version 5.5.4 (released 3 months ago), and the last dev release is actually older at version 5.0.0-dev.25.

Or should I have our team's monorepo pick up a more up-to-date release of Rush from another location?

**Comment by octogonz** [comment]
Most of the projects in **web-build-tools** publish twice a day.

Rush is special because when it has regressions they can be very disruptive.  So it gets published manually, and there's human validation beforehand.  As mentioned elsewhere, that hasn't been happening the past few months due to various nontechnical factors, so right now we're way far behind. This week @iclanton has been working on moving our publishing to run under a different account so we can manage it more efficiently going forward.

Rush 5 had a lot of breaking changes, so prior to its first stable release, we were publishing development builds using the `5.0.0-dev.25` nomenclature.  This allowed us to dogfood them internally.  (We're currently doing something similar with API Extractor 7, but instead using `npm dist-tag` to hold back the "latest" version as 6.x.)

Anyway, the first priority is to get the current master branch published asap. But going forward, as the user base continues to grow, it would make sense to regularly publish development builds of Rush, but still do manual testing for the official releases. We should investigate that.

**Comment by iclanton** [comment]
What @octogonz said.

**Comment by octogonz** [comment]
Validation for this release is tracked by PR https://github.com/Microsoft/web-build-tools/pull/1147

**Comment by octogonz** [comment]
Rush 5.6.0 has been released. Big thanks to @iclanton  who did most of the work!
