### ISSUE TITLE
[rush] Allow passing more different parameter characters in command-line.json

### ISSUE THREAD

**Issue by wbern** [Microsoft/web-build-tools#1193]
```json
    "parameters": [
        {
            "parameterKind": "flag",
            "longName": "--env.PROJECT_ENV=mode-a",
            "shortName": "-E",
            "description": "Will be passed onto webpack build configs",
            "associatedCommands": ["build", "rebuild"]
        }
```

>ERROR: JSON validation failed:
/home/whf962/Repos/double-mybusiness-fe/common/config/rush/command-line.json
Error: #/parameters/0
Data does not match any schemas from 'oneOf'
Error: #/parameters/0/longName (The name of the parameter (e.g. "--ve...)
String does not match pattern ^-(-[a-z0-9]+)+$: --env.PROJECT_ENV=mode-a
Error: #/parameters/0
Missing required property: alternatives

I would like to be able to pass the above into webpack. :-)

**Comment by octogonz** [comment]
This solution seems odd to me.  

The `--env.PROJECT_ENV=mode-a` syntax doesn't follows the conventions of **ts-command-line**, and except for someone who is very familiar with webpack, it doesn't seem particularly intuitive for end users.  It is describing implementation (*"assign computer environment variable X to have string literal value Y when invoking subtask Z"**) instead of functionality (*"Give me mode A"*)

Would it be better for the option to be something like `--mode-a`, and then the build script would map that to the appropriate webpack option?

@iclanton

**Comment by wbern** [comment]
@octogonz you're right in that it's unconvential, the problem is that I can't pass anything else to webpack to make it work (I can't pass a config because my config path is long and special and not always uniform among the packages)

I could make something that maps it for me, but in the end, I'd just end up using environment variable definitions (on nodejs/OS level) and it would just add (in my opinion) unnecessary complexity to the otherwise transparent nature of script contents.

I can find work-arounds for it but I don't know.. How come rush has so much role in deciding correct parameter symbols?

**Comment by octogonz** [comment]
> How come rush has so much role in deciding correct parameter symbols?

The **ts-command-line** library isn't perfect, but it has some philosophy that I think is good, and which explains some of the character of the Rush command line:

- The command line syntax aims to be simple and systematic, compared to other systems that support all sorts of weird notations that nobody can remember
- The syntax is strictly validated.  Whereas if you misspell an option, most other JavaScript command line parsers will silently ignore it (e.g. leaving you wondering why `npm install --globally` seemed to succeed but didn't do what you asked)
- Documentation is automatically generated, and the API strongly encourages writing docs for everything
- The system is designed to be composable:  The same parameter can be associated with multiple subcommands.  And extra commands/options can be injected dynamically by plugins, or in Rush's case, based on configuration from **command-line.json**.  In order to support this, the grammar needs to be designed so that it doesn't rely on context or ordering of tokens.

On top of this, Rush adds one more bit of philosophy: 

When I clone another team's monorepo for the first time, I want to type `rush -h` and see a nice, easy-to-understand list of commands that I can run, with options that make sense.  I don't want to have to dig through a huge README.md to figure out the super secret cocktail of "`--env.PROJECT_ENV=mode-a`" rocket science.  :-) Even if this means a little extra effort for the person setting up the repo, that investment is justified if it makes life easier for a casual contributor or new hire. 

> I could make something that maps it for me, but in the end, I'd just end up using environment variable definitions (on nodejs/OS level) and it would just add (in my opinion) unnecessary complexity to the otherwise transparent nature of script contents.

Normally this mapping happens in your toolchain.  People instinctively start out with a "toolchain" like this:

```
  "scripts": {
    "build": "rimraf ./lib/ && tsc"
  },
```

This works okay for tiny projects, but it breaks down pretty fast.  One day you'll come into the office and find that your innocent-seeming shell command has grown like a cancer:

```
  "scripts": {
    "build": "rimraf \"./lib/*\" && tsc && tslint --config tslint.json --project . --rules-dir node_modules/tslint-microsoft-contrib && jest",
  },
```

Ahhh!  If Rush's **command-line.json** wants to inject a custom command-line option for `tsc`, how's it supposed to figure out where in this string to insert the option?  A JSON string literal is not a good place to be writing source code.  And in a monorepo with 50 projects, you definitely don't want to copy+paste that string literal 50 times.

Our recommended best practice is realize that your build tools are serious software projects, and start from day one with TypeScript+tslint+Jest+etc:

```
  "scripts": {
    "build": "node_modules/my-tool-chain/lib/build.js",
  },
```

But if that's overkill for your situation, it's also fine to write a quick+dirty script like [this real world example](https://github.com/Microsoft/tsdoc/blob/6034bee3ec51c50682e087625023b939afeb42e2/tsdoc/package.json#L34):
```
  "scripts": {
    "build": "node ./build.js",
  },
```

Either way, this gives you an easy place to map those Rush parameters to Webpack options or environment variables or whatever else you like.  Coding in JavaScript is easy and fun.  Whereas coding shell expressions inside JSON string literals is not fun and not going to scale, and certainly should not be informing your `rush -h` design.

The above is mostly my own personal opinions, however.  If others have different opinions, I'm open-minded about it.

**Comment by wbern** [comment]
I had no idea about this, thanks for explaining it well for me and other potential users.

I think it might be tough to defend this for many potential Rush users, but I buy it, it's for the transparency on the root level. I'm gonna follow your advice.
