### ISSUE TITLE
[api-extractor] Trimmed API still has warnings about missing exports

### ISSUE THREAD

**Issue by jonathandturner** [microsoft/web-build-tools#1260]
When using api-extractor, I'm seeing cases where parts of the API are being trimmed, but they're still causing ae-forgotten-export warnings. 

I saw https://github.com/Microsoft/web-build-tools/issues/1235, which is similar to what I'm suggesting. For trimmed APIs, it feels like this suppression should be automatic, as the part of the API in question isn't in the final .d.ts file.

**Comment by octogonz** [comment]
Can you provide a repro branch that illustrates the problem? This would save some time

**Comment by jonathandturner** [comment]
Sure thing. You should be able to check out https://github.com/jonathandturner/trim-issue and then do npm install && npm run build

**Comment by jonathandturner** [comment]
I just noticed that you can get around this at the tsc level using:

```
"stripInternal": true /* Do not emit declarations for code with @internal annotation*/,
```

So it looks like this is in the case where you're using api-extractor to trim internals rather than tsc.

**Comment by octogonz** [comment]
> I just noticed that you can get around this at the tsc level using:
> 
> ```
> "stripInternal": true /* Do not emit declarations for code with @internal annotation*/,
> ```

We generally recommend against relying on `stripInternal`.  I'm guessing it was mainly introduced to support the compiler's own **typescript.d.ts** rollup, which is a simple concatenation (and probably works because compiler devs are very careful people heheh).  Consider this   input:

```ts
/**
 * For details please e-mail support@internalexample.com
 */
export class B {
}

/** @public */
export class A extends B {
}
```

The compiler will strip class `B` which leaves that symbol undefined for `A`.  Whereas API Extractor recognizes that the `@internal` substring is not a TSDoc tag in this context, and even if that was not the case, then it would report **ae-incompatible-release-tags** when it sees that `A`'s definition depends on `B`.

**Comment by octogonz** [comment]
> Sure thing. You should be able to check out https://github.com/jonathandturner/trim-issue and then do npm install && npm run build

Okay that was super helpful. Thanks!

To summarize, your repro looks like this:

```ts
/** @internal */
class Bar { }

/** @public */
export class Foo {
    /** @internal */
    public _bar(bar: Bar) {        
    }
}
```

The **ae-incompatible-release-tags** warning is reported because the class `Bar` is missing the `export` keyword.  An "internal" developer (who has access to the untrimmed rollup) will want to write code like this:

```ts
import { Foo } from 'your-lib';  // no trimming

const foo: Foo = new Foo();
const bar = ??? // <-- how do I call the Bar constructor?
foo._bar(bar); 
```

Thus, even though this internal developer's project can see the `Foo._bar()` method, and even though the `Bar` class declaration appears in the .d.ts file, there is no way for them to import it or construct it.

Why would someone want that situation?  I can think of a couple reasons:

1. `Bar` is not really a class, but some other construct such as an interface or type alias that can be constructed anonymously.  From an API design perspective, it's better for things to have names, but API Extractor should provide a way around it.  https://github.com/Microsoft/web-build-tools/issues/1235 is  tracking an enhancement that would generally allow suppressions. 

   OR
  
2. `_bar` is not really meant to be imported by any consumer.  The `@internal` designation is used to trim a declaration that is only ever imported by other files inside `your-lib`.  For this case, we've discussed introducing a separate TSDoc tag `@private`.  I thought there was a GitHub issue tracking that, but I can't seem to find it.  (Feel free to open one if you like.)

**Comment by jonathandturner** [comment]
The specific use case we have in mind for trimming is to create a public API rather than for making two different .d.ts rollups.  In this case, if a method is for internal use only, we would like to hide that method just like you'd hide data types that are internal representations and not meant for the user.

In your example, the user should not be constructing Bars, as Bar would be some internal representation.

For your #2 case, in the .d.ts file you should be able to just strip off the method, correct? Or are you trying to prevent subclasses from overwriting?

**Comment by jonathandturner** [comment]
After thinking about this a bit (with the help of @ramya-rao-a), I am coming around to it not making sense to use `@internal` to remove individual members of classes. Instead, private should be sufficient, as the compiler will not output the type into the .d.ts and should avoid the situation I was trying to work around in the example.

**Comment by octogonz** [comment]
Closing since the real world scenario being discussed turned out to need a different approach, and the possible improvements we discussed are tracked by separate issues.

@jonathandturner please reopen if I missed something or misinterpreted what you said. Thanks!
