### ISSUE TITLE
[rush] log output omits lines despite using --verbose or --debug in rush build

### ISSUE THREAD

**Issue by wbern** [microsoft/web-build-tools#1299]
I'd like to be able to see all console output if I specify one of these flags. To me, --verbose makes sense, but I'm open for ideas.

Right now me and my colleagues have to keep opening the .log files to see build results when the single important line for troubleshooting was omitted.

**Comment by wbern** [comment]
For reference: https://github.com/microsoft/web-build-tools/blob/2f707b9265d8137b703ba322d86e463f56b3e934/apps/rush-lib/src/logic/taskRunner/TaskRunner.ts#L464

**Comment by octogonz** [comment]
When using `--verbose`, my understanding was that the full output /is/ shown on the console.  The part that gets abridged is the summary at the end (where it explains which projects failed to build and why). The reason is that sometimes STDERR can have a large amount of text, so it wouldn't make sense to print it twice.

Is that not the case?

**Comment by wbern** [comment]
Oh you may be right.. I think I failed to check this.. I will get back when I can verify this again.

**Comment by rakeshpatnaik** [comment]
Closing this issue. Please reopen if you are still having the issue.
