### ISSUE TITLE
[api-extractor] Members with computed property names given the name '__computed'

### ISSUE THREAD

**Issue by rbuckton** [microsoft/web-build-tools#1301]
When the TypeScript binder encounters a computed property name, it gives it a symbol of either `__computed`, or `__@name` (where `name` is an ECMAScript well-known symbol name like `iterator`). For symbols named `__computed`, the actual name is deferred until the TypeScript checker performs "late binding" where it determines the type of the expression and uses that for the property name. 

Currently, `api-extractor` reports the names of these properties as either `__computed` or `__@name`. This results in a poor experience in several ways:

- The resulting member name is just known as `__computed` (or `__@iterator`, etc.) when run through `api-documenter` and DocFX
- Some types have *multiple* computed properties that end up named `__computed`, which `api-documenter` tries to use to generate a `uid` which is no longer unique (and results in `api-documenter` crashing).

A better experience would be for well-known symbols like `__@iterator` to converted to `[Symbol.iterator]`, and for `__computed` names, extract the underlying computed property expression from the excerpt text.

Here is an example that shows this issue:

```ts
// index.d.ts
export const x: unique symbol;
export const y: unique symbol;
export interface Foo {
  [x]: number;
  [y]: string;
}
```

The result is an entry for `Foo` with two properties named `__computed` and `__computed`.

**Comment by octogonz** [comment]
We definitely want to support ECMAScript symbols (aka computed properties).  The TSDoc parser already has some preliminary support for it (see [here](https://github.com/microsoft/tsdoc/blob/40e313e3e54375b927240ed0cac2c770f863360f/spec/code-snippets/DeclarationReferences.ts#L517) and [here](https://github.com/microsoft/tsdoc/blob/40e313e3e54375b927240ed0cac2c770f863360f/tsdoc/src/nodes/DocMemberSymbol.ts#L26)).

This is a somewhat involved feature, though.  We'd appreciate help with the design and implementation.  Thanks!

**Comment by rbuckton** [comment]
@octogonz: I went ahead and filed a PR for the necessary changes. 

Also, I'm curious if you've already filed issues against TypeScript for the necessary but missing (or non-public) TypeScript Language Service APIs referenced in the `TypeScriptInternals.ts` file. It would be worthwhile to track those so that we can investigate making them public in a future release.

**Comment by octogonz** [comment]
> Also, I'm curious if you've already filed issues against TypeScript for the necessary but missing (or non-public) TypeScript Language Service APIs referenced in the `TypeScriptInternals.ts` file. It would be worthwhile to track those so that we can investigate making them public in a future release.

I mentioned it to someone when we first introduced these workarounds (Ryan or Daniel, can't remember who).  Their thinking was that "everyone" uses the compiler internals.  They aren't really meant to be off-limits, but merely APIs with a weaker guarantee of remaining stable across releases, perhaps because their contracts aren't as well-defined. So we didn't pursue it.

BTW if you're looking to improve the compiler API, our most significant need is the stuff used by `ExportAnalyzer` as described in [this note](https://api-extractor.com/pages/contributing/architecture/).  These APIs are trapped inside a closure and not reachable by consumers, so we essentially had to reimplement some of the compiler's algorithms.
