### ISSUE TITLE
[api-extractor] Crash occurs for toolchain that emits the .d.ts file in the same folder as the .ts file

### ISSUE THREAD

**Issue by ninok** [microsoft/web-build-tools#1310]
I'm trying to run api-extractor on  [@here/harp-mapview](https://github.com/heremaps/harp.gl/tree/master/%40here/harp-mapview) but I get strange errors like this:

`Error: [/home/kettlitz/development/harp.gl/@here/harp-mapview/lib/Tile.ts#2097]: Unable to determine semantic information for this declaration`

Looking at the offending line there is not even a declaration:
`        if (this.projection.type === ProjectionType.Spherical) {
`
My api-extractor.json was created with api-extractor init and I only modified the `mainEntryPointFilePath` to point to the right file.

My tsconfig looks like this:
```
{
    "compilerOptions": {
        "target": "es6",
        "lib": ["es2017", "dom"],
        "module": "commonjs",
        "sourceMap": true,
        "declaration": true,
        "declarationMap": true,
        "strictNullChecks": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": false,
        "downlevelIteration": true
    }
}

```

**Comment by ninok** [comment]
Briefly looking into the code I saw that the error is thrown if the following method in TypeScriptInternals.ts returns undefined. Apparently it does not always work, but it should not get called for an if statement though.
```
  /**
   * Returns the Symbol for the provided Declaration.  This is a workaround for a missing
   * feature of the TypeScript Compiler API.   It is the only apparent way to reach
   * certain data structures, and seems to always work, but is not officially documented.
   *
   * @returns The associated Symbol.  If there is no semantic information (e.g. if the
   * declaration is an extra semicolon somewhere), then "undefined" is returned.
   */
  public static tryGetSymbolForDeclaration(declaration: ts.Declaration): ts.Symbol | undefined {
    const symbol: ts.Symbol = (declaration as any).symbol;
    return symbol;
  }
```

**Comment by octogonz** [comment]
API Extractor is designed to parse .d.ts files.  The bug here is that the analyzer is accidentally traversing into .ts files, I think because newer versions of the TypeScript compiler engine will analyze a .ts file even if we started from a .d.ts entry point.  

To fix this, API Extractor needs to disable that behavior somehow, or at least detect the .ts file extension so we can report a more informative error message.

Your project's build approach is not a common or advisable practice, however.  A modern build system should cleanly separate its "source code" from its "output files".  For example, I see that **harp-mapview/package.json** seems to have no "clean" command that would delete old outputs, perhaps because it's difficult to find them amidst the source code.  Leaving deadwood files around can lead to errors or nondeterminism.  Our convention is to put the source code under `./src` and the outputs under `./lib` or `./dist`, which makes cleanup easy:  simply delete the target folders.

If I do `yarn add @here/harp-mapview` in an empty folder and then run API Extractor on the result, it works fine (because the NPM package excludes the .ts files).  You could perhaps do that as a workaround until we can fix the API Extractor bug.

**Comment by octogonz** [comment]
@rbuckton @DanielRosenwasser  Any idea how we can tell the compiler to ignore the .ts files and use the .d.ts files instead?  I tried adding `"exclude": [ "**/*.ts" ]` to **tsconfig.json** but it didn't help.  :-P

**Comment by rbuckton** [comment]
You might be able to pass in a wrapped `CompilerHost` and replace the `readDirectory` and `readFile` (and possibly `resolveModuleNames` if necessary) methods to elide any non declaration files you come across.

**Comment by ninok** [comment]
Thanks. Setting proper output directory in tsconfig fixed the issue.

**Comment by octogonz** [comment]
PR #1341 adds the wrapped `CompilerHost`, so the remaining work to complete this fix should now be pretty simple.

**Comment by octogonz** [comment]
@gongt recently encountered the same thing in #1353. I'm starting to think we should fix this, since the problem isn't very obvious when people encounter it.

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/web-build-tools/pull/1357

**Comment by sedghi** [comment]
I had this problem and it appeared that I was using a class def as type, posting here for anyone looking for an answer. Below the `StackViewport` is a class def not a type def. 

![image](https://user-images.githubusercontent.com/7490180/171917484-bd2e51f4-9cad-4e19-944a-afe3712daf94.png)
