### ISSUE TITLE
[rush] Rush version fails to checkout master branch

### ISSUE THREAD

**Issue by Dalimil** [microsoft/web-build-tools#1318]
Running `rush version --bump -b master` in CI pipeline sometimes fails in the last step:
```
EXECUTING: git checkout master 
error: pathspec 'master' did not match any file(s) known to git
```
We believe this might be a race condition when someone else is updating master at the same time as described here: https://github.com/microsoft/web-build-tools/issues/944

A quick Google search suggests a quick solution of git fetching before the git checkout.

**Comment by ScottHysom** [comment]
In our case, the "someone else" is a separate CI pipeline that is committing a PR to master, since our master branch policy has it locked down to just pull requests. But we have 2 separate pipelines: one to perform pull requests, and another to perform the publish of packages, which includes bumping the versions.
