### ISSUE TITLE
[rush] Faster fixes for missing dependencies

### ISSUE THREAD

**Issue by jeffsee55** [microsoft/web-build-tools#1358]
When a package I'm installing has several missing dependencies I end up running `rush update --full` over and over after modifying the `common/config/rush/pnpmfile.js` when really all I want it to do is install that additional dependency. Is there a faster way to update dependencies?

**Comment by octogonz** [comment]
This is the problem with designing config files to be an executable computer programs instead of simple data.  Executable code is more "flexible", but there is no way to analyze changes, or perform incremental updates.  It's not even easy to validate that its output is internally consistent.

This is a design issue with PNPM (see https://github.com/pnpm/pnpm/issues/949#issuecomment-349747876).  There isn't a straightforward way to fix it in Rush.  I'd suggest to open a PNPM issue instead.

**Comment by jeffsee55** [comment]
Thanks for the information, that linked comment is really informative. From my end happy for this to be closed 👍

**Comment by iclanton** [comment]
Seems like this is resolved. Closing this issue.
