### ISSUE TITLE
@defaultValue is not emitted by api-extractor

### ISSUE THREAD

**Issue by csr632** [microsoft/web-build-tools#1463]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**

this is the `xxx.api.json` emitted by api-extractor: 
![image](https://user-images.githubusercontent.com/18747423/63142482-956bd480-c01c-11e9-8def-b1cfb119ca41.png)
I have a `@defaultValue` block for property signature, but api-extractor doesn't extract it into `xxx.api.json`.
I expect a property like `defaultValue` in the `xxx.api.json`. So that I can use it in my custom api-documenter.

**Comment by octogonz** [comment]
@csr632  The .api.json file stores the doc comment as a text string in the `"docComment"` field, as seen above.  If we stored a parsed tree, the file would be significantly larger.

Your custom tool should not be trying to parse this JSON file.  Instead, it should use the [@microsoft/api-extractor-model](https://www.npmjs.com/package/@microsoft/api-extractor-model) library to load it.  This library provides a nice API for accessing the document structure, including the parsed TSDoc comment.

The `ApiPropertySignature` class will have an inherited property called [ApiDocumentedItem.tsdocComment](https://github.com/microsoft/web-build-tools/blob/442bbc1f8c6e1c4f7c20043e548c13f3d949db4d/apps/api-extractor-model/src/items/ApiDocumentedItem.ts#L60), and this has a collection [DocComment.customBlocks](https://github.com/microsoft/tsdoc/blob/746a8fb8fe89790107325c79e9077cdc8c83546a/tsdoc/src/nodes/DocComment.ts#L120) containing block tags such as `@defaultValue`.  The `@defaultValue` is not an immediate member of `DocComment` because its standardization level is ["extended"](https://github.com/microsoft/tsdoc/blob/746a8fb8fe89790107325c79e9077cdc8c83546a/tsdoc/src/details/StandardTags.ts#L69).

Let me know if this solves your problem.

**Comment by csr632** [comment]
Thanks for defailed explaination! I do use `@microsoft/api-extractor-model` but I forgot `DocComment.customBlocks`! I finally solve my problem by imitate `api-documenter`:
https://github.com/microsoft/web-build-tools/blob/76017371fcc1151fc6a31f694e1098e220a4a0e9/apps/api-documenter/src/documenters/MarkdownDocumenter.ts#L224
