### ISSUE TITLE
TypeScript 2.4

### ISSUE THREAD

**Issue by NickSevens** [Microsoft/web-build-tools#262]
Hello, is there a plan/procedure to make the build use TypeScript 2.4 instead of 2.2.2?
gulp-core-build-typescript will always compile using 2.2.2 at the moment.

Thank you.

**Comment by pgonzal** [comment]
Yes, we are planning to upgrade to 2.4 soon.  Currently compiler migrations are fairly expensive for us, because we have a large number of projects.

We frequently hear from eager adopters who want to stay current with the latest compiler releases.  To address this, we are planning to introduce a configuration option for switching between the "latest" and "stable" compiler.  (We cannot simply drop in arbitrary compiler builds via package.json, because certain components of our toolchain interact with the compiler and usually need some fixes/debugging to work with a new version.)

**Comment by NickSevens** [comment]
I did manage to use another typescript compiler by adding the following in `gulpfile.js`:
```
let typescriptConfig = require("@microsoft/gulp-core-build-typescript/lib/TypeScriptConfiguration").TypeScriptConfiguration;
typescriptConfig.setTypescriptCompiler(require("typescript"));
```
This ensured the compilation used the npm installed TypeScript version.

**Comment by pgonzal** [comment]
If it works for you, feel free to use that option.  However, we cannot support any incompatibilities that may arise (e.g. tslint rules behaving incorrectly, api-extractor crashes, etc).

**Comment by NickSevens** [comment]
In the end, decided to work around the issues I had with 2.2, instead of changing the compiler version.
Seems to be more reliable, and indeed would keep the compatibility in check.
Thanks for the info though.
