### ISSUE TITLE
[api-extractor] Namespace doesn't have exported members

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/web-build-tools#293]
Code sample:
```ts
/**
 * @public
 */
export namespace CoolStuff {
    /**
     * Yet another sum function.
     */
    export function YetAnotherSumFunc(x: number, y: number): number {
        return x + y;
    }

    export const a: string = "namespaced a";
}
```

Searching in the source code, I only found: [ApiModuleVariable](https://github.com/Microsoft/web-build-tools/blob/master/libraries/api-extractor/src/definitions/ApiNamespace.ts#L99). 

I think, `api-extractor` should support interfaces, enums, classes etc, in namespaces.

__EDIT:__ 
```ts
if (!(followedSymbol.flags === ts.SymbolFlags.BlockScopedVariable)) {
          this.reportWarning(`Unsupported export "${exportSymbol.name}" ` +
            'Currently the "namespace" block only supports constant variables.');
          continue;
}
```
Strangely enough, I haven't received a warning in `api-extractor` runtime.

**Comment by pgonzal** [comment]
API Extractor's handling of namespaces is a new feature that was aimed at a fairly restricted scenario ("[API Extractor now supports tables of constants](https://github.com/Microsoft/web-build-tools/wiki#may-1-2017---api-extractor-now-supports-tables-of-constants)").  For a long time, the TypeScript "module" and "namespace" keywords were basically deprecated, and only needed for describing typings of libraries.

As pointed out in that announcement, in most cases there is a mostly equivalent representation using classes (as far as what the API consumer sees in their IntelliSense).  To the extent that two alternative syntaxes are equivalent, I personally strongly prefer to have "[one obvious way](https://www.python.org/dev/peps/pep-0020/)", because this makes life significantly easier for people who read existing code (despite annoying some people who write new code).  Reading is a more important scenario than writing.  :-)

There was internally a bunch of debate about this.  Arguments for namespaces:
- EcmaScript is normalizing that syntax
- It avoids emitting a useless constructor definition, which is slightly more efficient
- It clearly communicates that the API not really a class

Arguments for "static classes" like from C# and Java:
- Namespaces don't mark their members as constant in the type system, e.g. you can do `CoolStuff.YetAnotherSumFunc = undefined`.  (There is a workaround for this, but it is ugly.)
- Namespaces cannot have private members, instead they have closure variables, which cannot be inspected in a debugger
- Also, unit tests have no way to access closure variables, whereas class members are reachable (e.g. by typecasting, or by making them protected and accessing them via a subclass)
- Supporting namespaces requires nontrivial work (e.g. extending the JSON schema, adding new templates to our documentation pipeline), and shouldn't be prioritized if there is an easy workaround

That's why we ended up where we are now, although if there is a lot of demand for namespaces, we would certainly reconsider it.

> Strangely enough, I haven't received a warning in api-extractor runtime.  

These warnings are emitted in your *.api.ts file.  We take that approach because "fixing" this sort of problem might require a disruptive restructuring of your code.  We wouldn't want to add noise to everyone's build for an issue that may be unrealistic to fix in some cases.

**Comment by pgonzal** [comment]
\+ @dzearing  who was also interested in namespaces

**Comment by MartynasZilinskas** [comment]
Interesting. I guess I will have to discuss about this with @DovydasNavickas.

>These warnings are emitted in your *.api.ts file. We take that approach because "fixing" this sort of problem might require a disruptive restructuring of your code. We wouldn't want to add noise to everyone's build for an issue that may be unrealistic to fix in some cases.

Fair enough.

**Comment by pgonzal** [comment]
Since there have been no comments, I'm closing this issue.  Feel free to reopen it if you have further thoughts.
