### ISSUE TITLE
Karma extensibility for reporters

### ISSUE THREAD

**Issue by estruyf** [Microsoft/web-build-tools#374]
Is it possible to include extensibility for using additional reporters like for example: `karma-html-reporter`?

This makes our unit-tests a lot better and easier to report.

**Comment by nickpape-msft** [comment]
We are looking into it. If you are just using `@microsoft/web-library-build` then you should just be able to modify your karma config. If you are using `@microsoft/sp-build-web` then yes, we need to add some extra points of extensibility!

**Comment by qz2017** [comment]
Ping. @estruyf , are you using web-library-build and does @nickpape-msft 's suggestion work for you?

**Comment by estruyf** [comment]
I achieved it by extending the current Karma config for `@microsoft/sp-build-web` as follows: https://github.com/SharePoint/sp-dev-fx-controls-react/blob/master/config/karma.config.js

**Comment by pgonzal** [comment]
I'm closing this issue, since there is a workaround.  @estruyf FYI longer term we are looking to switching **sp-build-web** to use Jest, so we haven't been actively improving the Karma task lately.  (It is also still using a fairly old version of Karma.)  So we probably will not incorporate this improvement into `sp-build-web.`

BTW if you want try Jest, [web-library-build-test](https://github.com/Microsoft/web-build-tools/tree/master/build-tests/web-library-build-test) and PR #450 show some examples of how to convert.  Basically you just add config/jest.json, remove the karma/mocha definitions from your package.json, and fix up your assertions to use Jest's types.
