### ISSUE TITLE
When rush installs NPM it does not use the NPM registry specified in common/config/rush/.npmrc

### ISSUE THREAD

**Issue by jbrekelmans** [Microsoft/web-build-tools#691]
The title summarises what I think is an issue.
The steps to reproduce on a Linux machine can be found here: 
https://gitlab.com/jbrekelmans/microsoft-rush-bug
It appears the user .npmrc file is respected and can be configured to workaround this issue

**Comment by pgonzal** [comment]
@iclanton FYI

**Comment by jbrekelmans** [comment]
> Are you behind a proxy that blocks you from installing packages from the internet?

Yes, I am on an internal network and cannot access http://registry.npmjs.org/, but we do have a proxy.

> Is this issue for a local developer machine, or is it for an automated CI process?

Both local developer machines and our CI process have this issue. We want the NPM registry proxy configuration to be on GIT to ensure builds are consistent between CI and local, there is no hard dependency on CI agent or developer machine configuration and developer setup is easier.
I'm very excited to hear about Rush 5 and ```install-run-rush.js```, this is exactly what I'm looking for!

Thanks @pgonzal

**Comment by pgonzal** [comment]
Awesome.  I'll reply to this thread as soon as we've published the beta with `install-run-rush.js`.  @iclanton is pretty close to done with his PR.

**Comment by pgonzal** [comment]
Give `@microsoft/rush@5.0.0-dev.23` a try.  After you update your `"rushVersion"` field in rush.json, run `rush install` which will create the files in the **common/scripts** folder.  You should add them to Git.

Then you can invoke them similar to what we're doing in our [.travis.yml file](https://github.com/Microsoft/web-build-tools/blob/master/.travis.yml).

If you are still on Rush 4, here's a quick list of breaking changes in Rush 5:
- `rush generate` was replaced by `rush update --full`
- A number of command-line options have changed, e.g. `rush install --clean` is now `rush install --purge`
- The file format for **command-line.json** has changed.
- The **pinned-versions.json** file was replaced by **common-versions.json** with some minor changes.
- When rush invokes package.json scripts, the NPM environment variables are no longer passed through

**Comment by jbrekelmans** [comment]
Awesome, thanks

**Comment by jbrekelmans** [comment]
I found a pretty good workaround (Bash):
```
# Override the registry set in global .npmrc and user .npmrc
export npm_config_registry
npm_config_registry='https://my-registry.example.com'
# Ensure the correct CA certificate are used to authenticate the registry
export npm_config_cafile
npm_config_cafile='/path/to/pem_bundle.pem'
rush install
```
These environment variables will override ~/.npmrc and the global npmrc [and won't be filtered](https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/utilities/Utilities.ts#L472) because they are lower case.

**Comment by pgonzal** [comment]
> Anyway, I installed @microsoft/rush@5.0.0-dev.23 without the proxy and then turned on the proxy. But again it is not using the registry specified in the .npmrc file (this time not using install-run-rush.js but using the CLI directly).

This is the issue I mentioned above.  When you do this:

```
C:\>npm install -g @microsoft/rush
C:\>cd my-repo
C:\my-repo>rush install
```

...under their current design, Rush will read **C:\my-repo\rush.json** to determine the repo's configured Rush version, and then it will install that globally in folders like **C:\Users\you\.rush\rush-5.0.0** and it will install NPM in **C:\Users\you\.rush\npm-5.4.2**.  It's done globally because some people have lots of working folders, and it would seem inefficient to install Rush for each one.  However, a global installation cannot depend on settings from **C:\my-repo\config\rush\.npmrc** because that might be different for each working folder.

By contrast, the **install-run-rush.js** script does support .npmrc because it installs things locally under **C:\my-repo\common\temp**.  This is desirable for automated environments, where isolation is important.

That's the current state of things.  However your "no internet access" situation here is very valid and something we didn't consider very well.  Even though you have a workaround, I'd like to think about a better way to handle it.  (Also the NPM environment variables might not work for people whose .npmrc needs to specify mappings for multiple registries.)  

Some ideas:

1. Provide a rush.json option that causes NPM/Rush to always get installed under common/temp instead of globally
2. Install globally, but somehow include the registry in `C:\Users\you\.rush\*\last-install.flag` so that if it changes, the dependency can get reinstalled using the new configuration

@iclanton

**Comment by pgonzal** [comment]
Maybe I'm being too formalized in my thinking here.  We could also just:

3. Ignore the hypothetical concern of different registries having inconsistent versions of Rush/NPM.  When installing globally, Rush will try to use the .npmrc file from the local repo, and if it's able to install something, then we assume whatever we got is good enough for all the other Git working folders on the machine.

**Comment by jbrekelmans** [comment]
OK, I'm on the same page now.

To deal with NPM registries disagreeing on the files that make up a version of Rush/(P)NPM you can:
1. store the integrity of the Rush/P(NPM) installation on the repository (inside common/config/rush)
2. compare it against the global installation of the machine (```C:\Users\you\.rush```) when rush runs
3. take appropriate action if an inconsistency is detected (e.g. warn or fail)
This is similar to option 2, but still accepts different registries.
This would also guard against manual modifications of ```C:\Users\you\.rush```.

This is more user-friendly than option 1 (e.g. still no waste of disk space and the global installations can still be cached), but may be more complex.

**Comment by pgonzal** [comment]
@jbrekelmans we ended up going with my approach 3.  After some thought we decided that it's reasonably safe to use a local .npmrc to install in a shared instance in a global location.  Essentially we're merely assuming that a private registry cannot republish a specific package version with tampered contents that are different from the official version on the npmjs.com registry.  This seems like a pretty reasonable assumption.

PR https://github.com/Microsoft/web-build-tools/pull/700 has been published as `@microsoft/rush/5.0.0-dev.24`.  Please give it a try and see if it fixes your issue.

**Comment by jbrekelmans** [comment]
Awesome, will give it a go Monday (UTC+10)

**Comment by jbrekelmans** [comment]
OK, the issue is solved now! Thanks

**Comment by RJahnavi** [comment]
@pgonzal Is there a way to specify the path in which NPM get's installed during automated CI process. Right now it get's installed to "C:\Users\<server>\.rush\"  but we prefer to install it in a different location.

**Comment by pgonzal** [comment]
If this is for a CI machine, you could also consider using [install-run-rush.js](https://rushjs.io/pages/maintainer/enabling_ci_builds/)
