### ISSUE TITLE
[rush] Please add ./node_modules/.bin to the path for custom commands 

### ISSUE THREAD

**Issue by jbcpollak** [Microsoft/web-build-tools#706]
When I add a command to `command-line.json` it would be nice if we could assume anything in `node_modules/.bin` was already on the path, the same way npm works. This would minimize the effort to convert our projects, as well as help simplify our package.json files.

**Comment by pgonzal** [comment]
+1 We should definitely improve this.

Today the way Rush spawns processes is [somewhat hacky](https://github.com/Microsoft/web-build-tools/blob/2c4e91ad014248be176d8ed6b392d95d093f9abc/apps/rush-lib/src/utilities/Utilities.ts#L322), but the fix should still be pretty straightforward.  We've been aware of this issue for a while, but it keeps getting procrastinated (because historically we've been using gulp tasks instead of package.json scripts, although this summer we will be migrating away from Gulp).  Fixing this would also benefit the new `rushx` command in Rush 5.

If someone else wants to contribute a PR, that would be welcome as well!

**Comment by pgonzal** [comment]
BTW we recently started work on a package [@microsoft/rushell](https://github.com/Microsoft/web-build-tools/tree/master/libraries/rushell) that will be a reboot of how Rush invokes shell commands.

**Comment by HipsterZipster** [comment]
Can't wait this one!

**Comment by pgonzal** [comment]
#764 is the first half of this fix

**Comment by pgonzal** [comment]
We're going to prioritize this fix... it's embarrassing :-)

**Comment by octogonz** [comment]
@hh83917 encountered this as issue https://github.com/Microsoft/web-build-tools/issues/1059

**Comment by davidyxu** [comment]
Was curious about the status of this issue, it looks like you're planning to refactor how rush runs shell commands entirely. What's the expected timeline for rushell to be available?

If it's going to be awhile before rushell is complete, is there any sort of quick temporary fix that could be added to rushx (e.g. inject `./node_modules/.bin` into the PATH environment variable)?

**Comment by octogonz** [comment]
> Was curious about the status of this issue, it looks like you're planning to refactor how rush runs shell commands entirely. What's the expected timeline for rushell to be available?

Rushell is a really fun project to work on ( :-) ), and I think long-term I think it's the best way to ensure consistent behavior across OS's.  On Windows it can also improve performance by reducing the number of processes that get spawned.  But Rushell is something that I was working on in my spare time. It's not currently part of any tracked milestone.  So I wouldn't want to block any important fixes behind it.

> If it's going to be awhile before rushell is complete, is there any sort of quick temporary fix that could be added to rushx (e.g. inject `./node_modules/.bin` into the PATH environment variable)?

Absolutely.  Other than the process spawning code being a bit messy, this should be a fairly simple PR.  I had  tagged it as "help wanted / effort easy".  It's frankly embarrassing that we still haven't gotten around to fixing this, and I regret releasing `rushx` with such an annoying flaw.  If someone from the community wants to make a PR, that would be awesome.  Otherwise I'll bring it up again and see if one of the Rush maintainers can get to it.  (We've just been spread pretty thin lately, so progress in general has unfortunately been a little slow.  I'm hoping that will clear up pretty soon.)

**Comment by octogonz** [comment]
This was published with Rush 5.6.0.

**Comment by octogonz** [comment]
@davidyxu thanks again for taking the initiative to get this fixed!  I've stopped using `npm run` entirely and can now use `rushx` for everything.  It saves me 2 keystrokes every time I run a command!  :-D

**Comment by davidyxu** [comment]
:) Wish I could take credit, but it was all you and @iclanton 
Thanks for open sourcing rush, hopefully I'll make some contributions in the future!
