### ISSUE TITLE
[api-extractor ]support for @defaultvalue or @default and @type

### ISSUE THREAD

**Issue by RueDeRennes** [Microsoft/web-build-tools#720]
is there any support for @defaultvalue or @default and @type?
in my usecase: 
`
/**

     * Gets or the `role` property. The role is depending on the actions count.
     * Posible values are: `dialog` | `alertdialog` | `alert`
     * @public
     * @type `boolean`
     * @defaultvalue `''`
     */
    readonly role: string;
`

**Comment by pgonzal** [comment]
What is the role of `@type`, given that the TypeScript language already has a full type system?

The `@default` tag seems like a pretty useful feature. Could you also open an issue for the [TSDoc](https://github.com/Microsoft/tsdoc) project to propose adding `@default` to the standard?

**Comment by pgonzal** [comment]
I opened https://github.com/Microsoft/tsdoc/issues/27 to track this.  I'm closing this issue since `@type` seems to be already handled by the type system (although note that there is a [JSDoc-in-JavaScript scenario](https://github.com/Microsoft/tsdoc/issues/23) that might be relevant.

Feel free to reopen this issue if you have more questions specific to API Extractor.
