### ISSUE TITLE
[rush] Improvements to approvedPackagesPolicy?

### ISSUE THREAD

**Issue by scsewall** [microsoft/web-build-tools#749]
We essentially have 4 different types of approved packages:

1. Approved for the frontend (browser)
2. Approved for the backend (Node.js-based process)
3. Approved for either frontend or backend.
4. Approved as a devDependency (not used at run-time)

For example, we have UI-related packages that are frontend-only and database-related packages that are backend-only and utility packages that can run in either. Do you have this frontend vs. backend notion in your packages?  Then there is the dependency vs. devDependency notion. The review for frontend and backend (run-time) is different than for devDependencies. For example, "mocha" should only be a devDependency and does not belong in the frontend or backend list.  However, something like "yargs" it could be unclear whether the backend actually depends on it at runtime or whether it is just a devDependency for a test script.  That is an example of why I would like to distinguish between dependencies and devDependencies. Maybe it would be enough for the *-approved-packages.json report to indicate why it was pulled in (via a dependency or devDependency) to help with the review.

It would also be nice if comments about each package could be preserved somehow.

Extracting the license type from the dependent package could also help with the legal review.

**Comment by nickpape-msft** [comment]
We definitely have a similar situation in our internal repo. The original split was between "browser/non-browser", although we conflated devDependencies and your second category ("approved for backend") because we don't have any non-devDependency server/Node.js code. We also originally were just trying to distinguish packages that were going to browser from packages that were never going to browser, so if it was used in both (e.g. your number 3 category), we just considered it a "browser" package.

So that's a bit of the history.

> It would also be nice if comments about each package could be preserved somehow.

We could probably achieve this. IIRC when this feature was added we hadn't standardized on `jju` as our JSON loading library. That library does support preserving comments in JSON files, so it may be trivial to add support for this. Alternately, we could introduce an optional field called "comment" that would just be part of the JSON.

---

Those 2 things being said, there still may be a way to immediately achieve your goal with the existing implementation, although it isn't incredibly clean. There is a concept of `allowedCategories` (in *-approved-packages.json) and `reviewCategory` (in rush.json). Basically each project can be marked in a particular review category. You can mark your frontend packages as the "frontend" review category, the server packages as "backend", and the tools dependencies as "tooling". Then you could ignore the names of the files and treat `browser-approved-packages.json` as "directDependencies" and `nonbrowser-approved-packages.json` as "devDependencies".

Category 1 - appears in `browser-approved-packages.json` marked as "frontend" category
Category 2 - appears in `browser-approved-packages.json` marked as "backend" category
Category 3 - appears in `browser-approved-packages.json` marked as "frontend" and "backend" categories
Category 4 - appears in `non-browser-approved-packages.json`, the category doesn't matter

If you are interested in this approach I can leave more info on how to setup and use `approvedPackagesPolicy`/`allowedCategories`/`reviewCategories`.

**Comment by scsewall** [comment]
I would vote for a "comment" field as part of the JSON.  It would be easier to generate reports that way.

I will give your frontend / backend reviewCategory suggestion a try.  Seems like that could work for me.  Thanks.
