### ISSUE TITLE
Inconsistent usage of `where` command on Windows

### ISSUE THREAD

**Issue by nickpape-msft** [Microsoft/web-build-tools#759]
There is some code in [BaseCmdTask.ts](https://github.com/Microsoft/web-build-tools/blob/6bcddb75ad9ee2fcb9cc86b9462f95396206a138/core-build/gulp-core-build-typescript/src/miniTasks/BaseCmdTask.ts#L67) that is trying to launch `node.exe`. Currently it is taking the last thing that appears from the which command. However, this will cause problems if there are multiple copies of `node.exe` with different versions in your PATH.

This code was originally lifted from some code in [install-run.js](https://github.com/Microsoft/web-build-tools/blob/dcd5c2760ee581d42207aa0cac89e76712cdd97f/apps/rush-lib/src/scripts/install-run.ts#L128) which is trying to launch something with a `.cmd` ending -- and the `.cmd` version is typically the second thing on the path.

We need to fix the issue in BaseCmdTask.ts, and then standardize the repeated code to solve this issue more generically [likely in rushell].

@iclanton @pgonzal FYI

**Comment by pgonzal** [comment]
> There is some code in BaseCmdTask.ts that is trying to launch node.exe. 

Hmmmm... executing the `where` tool is pretty clunky.  It probably also introduces a security vulnerability, e.g. if a `where.bat` appears anywhere in the shell search path.  For finding `node.exe`, shouldn't we simply use the `process.execPath` path from the parent's Node engine?

> We need to fix the issue in BaseCmdTask.ts, and then standardize the repeated code to solve this issue more generically [likely in rushell].

I have a [branch](https://github.com/Microsoft/web-build-tools/commits/pgonzal/rushell-execute) that will introduce an `Excecutable` API that should become our solution for the general problem, including searching the default file extensions on Windows.

That work got blocked because *a certain person* still hasn't gotten around to reviewing my earlier PR https://github.com/Microsoft/web-build-tools/pull/754 .  :-P
