### ISSUE TITLE
Issues with git policy checks in CI in Rush 5.0.5

### ISSUE THREAD

**Issue by christiango** [Microsoft/web-build-tools#809]
I tried upgrading to rush 5.0.5 and I am getting the following error on install for CI builds.

Unable to determine your Git configuration using this command:
2018-09-01T01:05:53.3516502Z 
2018-09-01T01:05:53.3516502Z     git config user.email

I worked around it by using the "--bypass-policy" flag for install, but publish fails with the same reason and bypass policy is not accepted there.

Since our repo does not have a git policy assigned in rush.josn, I would not expect this error to surface in CI builds.

**Comment by pgonzal** [comment]
Did you try 5.0.6? I believe this was already fixed in PR https://github.com/Microsoft/web-build-tools/pull/806

**Comment by christiango** [comment]
I'll take a look later today at 5.0.6. We're currently unable to do npm install because of a VSTS outage.

**Comment by pgonzal** [comment]
Since Rush is open source, you could upgrade like this:

1. Temporarily rename `C:\Users\you\.npmrc` to something else
2. Run `npm install -g @microsoft/rush`
3. Update the Rush version in **rush.json**,  and then `rush install` -- it will successfully install Rush in the cache, but fail to install your private packages
4. Rename your **npmrc** file back to `C:\Users\you\.npmrc`
5. Now `rush install` should work with private packages (assuming what you need is in the cache already)

**Comment by christiango** [comment]
Works with 5.0.6! Thanks @pgonzal
