### ISSUE TITLE
[rush] does not support node version 10.11.0

### ISSUE THREAD

**Issue by yudapc** [Microsoft/web-build-tools#840]
I am using:
```
node: 10.11.0
npm : 6.4.1
```

After `checkout` this repository, I tried to run `rush update`. But there are errors about node version.

```
ERROR: Your dev environment is running Node.js version v10.11.0 which does not meet the requirements for building this repository.  (The rush.json configuration requires nodeSupportedVersionRange=">=6.9.0 <7.0.0 || >=8.9.4 <9.0.0")
```

**Comment by pgonzal** [comment]
This is by design.  NodeJS 10.x is [currently unstable](https://nodejs.org/en/download/releases/).  It won't graduate to stable (LTS) until sometime in October.

This repo's **rush.json** is configured to warn about unstable NodeJS releases. (In the past, we wasted too much time investigating errors that people had reported, which turned out to be NodeJS regressions.)  The [recommended solution](https://github.com/Microsoft/web-build-tools/wiki/Contributing-to-this-repo) is to use an installer such as **nvm** that makes it easy to switch between different NodeJS releases.  However, if you don't want to do that, you can suppress the warning by modifying your **rush.json** file to delete the [nodeSupportedVersionRange](https://github.com/Microsoft/web-build-tools/blob/e799364eee904c54ce1d05b2b6a4836d799cf20b/rush.json#L6) field.  (Just remember not to commit this change to your branch. :-) )

**Comment by yudapc** [comment]
Thank you for the explanation. 👍
