### ISSUE TITLE
[rush] Allow publish of unchanged package

### ISSUE THREAD

**Issue by xpepermint** [Microsoft/web-build-tools#857]
Lerna allows you to publish all the packages under the same version. That's desirable especially for frameworks where a user knows which framework version he/she is targeting. As I can see RushJS only publish packages based on actual changes thus package versions are individual per package.

It would be great to enable bulk publishing of all the packages under the same version regardless of the changes.

**Comment by pgonzal** [comment]
Rush has this feature, but you need to define a "version policy". It's not very well documented through. Let me follow up with more details.

**Comment by pgonzal** [comment]
Okay so it is sort of mentioned here:

https://rushjs.io/pages/maintainer/publishing/

But basically what you do is create a file **version-policies.json** and then add a policy whose definition name is `lockStepVersion`:

```json
[
  {
    "policyName": "myFramework",
    "definitionName": "lockStepVersion",
    "version": "1.2.3",
    "nextBump": "minor"
  }
]
```

...then you go in **rush.json** and associate projects with this policy:

```json
  "projects": [
    {
      {
        "packageName": "library-a",
        "projectFolder": "libraries/library-a",
        "versionPolicyName": "myFramework"
      },
      {
        "packageName": "library-b",
        "projectFolder": "libraries/library-b"
      },
      {
        "packageName": "library-c",
        "projectFolder": "libraries/library-c",
        "versionPolicyName": "myFramework"
      },
    }
  ]
```

A "version policy" is basically a group of packages that publish together.  (We're planning in the future to rename this feature to something like "publishingGroup" to make that more clear.)  Note in my example above that **library-a** and **library-c** would publish with lockstepped (i.e. identical) version numbers, whereas **library-b** is NOT part of the policy.  It's designed this way because, in a large monorepo, you will typically have many different clusters of projects with different models/workflows for how they get published.

Anyway, the lockstep packages will all get the same version.  The version they get is determined by the `"version"` field in **version-policies.json**, and the version is bumped based on the `"nextBump"` field.  This field is stored in a JSON file so that e.g. when you create a 1.2.0 release branch, you can configure that branch to publish with patch-bumps (or prelease bumps, or whatever depending on the type of branch).

Hopefully that helps.  Let me know if you have more questions.

@qz2017

**Comment by xpepermint** [comment]
Thank you so much @pgonzal. If I have issues with this I'll reopen this issue.
