### ISSUE TITLE
[rush] Class checks using `instanceof` return `false`

### ISSUE THREAD

**Issue by xpepermint** [Microsoft/web-build-tools#858]
It seems that using `instanceof` for checking classes inside dependencies can return an unexpected result.

Here is the commit which was needed to make the package work with my personal NodeJS project which uses RushJS: https://github.com/hayspec/framework/commit/0146a44cffca89e73828c9a8e452b5d25b73951d

**Comment by xpepermint** [comment]
I'm digging for hours and I can't reproduce it after I removed all the node_modules, log and lock files. It must have been some sort of cache. I did not try the `purge` command - maybe it would help.

I'm closing this issue for now. Thanks, @pgonzal for now.

**Comment by pgonzal** [comment]
>  I can't reproduce it after I removed all the node_modules

Stray *node_modules* folders would also cause this problem, due to the [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/) problem.  Basically your `require()` statement can accidentally find the library in an old **node_modules** folder, which can lead to the same problem -- where you are mixing together two different definitions of the same class.
