### ISSUE TITLE
[API Extractor] - `[object Object]` replacing special characters 

### ISSUE THREAD

**Issue by AlexJerabek** [Microsoft/web-build-tools#901]
API Extractor is replacing special characters with `[object Object]` when outputting JSON files. There may be more cases, but I've noticed this behavior for `\`, `{`, and `}`. 

[PR showing issue](https://github.com/OfficeDev/office-js-docs-reference/pull/226/files)
[Docs showing issue](https://review.docs.microsoft.com/en-us/javascript/api/excel/excel.charttitle?view=office-js&branch=elizs-get-latest#getsubstring-start--length-)

**Comment by pgonzal** [comment]
@AlexJerabek  Thanks for reporting this!  The problem occurs when TSDoc returns error nodes because the symbol charactrers are not escaped properly.  (For example in `\n` should really be written `\\n` to make it clear that you really want a literal backslash and were not trying to make a TSDoc newline.)  These "errors" are supposed to be rendered as literal text on the web site (as you expected), but there was a bug with the text processing.

We never encountered this because our own doc comments are always perfectly escaped.  :-P

**Comment by pgonzal** [comment]
This was published as API Extractor 6.0.8
