### ISSUE TITLE
[api-extractor] Would like to be able to use api-extractor for API reviews without having to opt into documentation generation.

### ISSUE THREAD

**Issue by scsewall** [Microsoft/web-build-tools#920]
The API review part of api-extractor looks interesting, but the documentation comment validation part is getting in my way. I have an existing API documentation pipeline that I don't want to change right now.  That pipeline starts with typedoc plus a few custom tags and then uses internal tools to create an HTML-based website.

Ignoring the error logs and error return code (caused by custom tags, different formatting standard for @param, etc.) is not an acceptable solution because I'd have to hack the CI build scripts too much.

Ideally there would be a way to make the documentation generation part of api-extractor optional and just generate the api.ts file.

**Comment by pgonzal** [comment]
I've also heard this request from teams that want to track their API, but don't have any interest to generate a documentation web site.

As discussed on Gitter, this should wait until AE7 is released, to avoid a merge conflict.

**Comment by AlexGhiondea** [comment]
@pgonzal is there an update on this?

**Comment by pgonzal** [comment]
I've removed the blocked tag, since the AE7 branch has been merged.  However it's still in "beta".  My top priority is to fix a few remaining issues that are preventing us from removing the "beta" label (basically oriented towards the milestone of enabling AE7 for the **office-ui-fabric-react** project.) Then I'll be able to work on this issue.  Your issue is definitely a priority, since as I mentioned a lot of other people have asked for it, too.

I apologize for these delays.  The new analysis features that we introduced in AE7 turned out to have a ton of special cases that have taken a much longer than expected to work through.  :-)

**Comment by octogonz** [comment]
[PR #1120](https://github.com/Microsoft/web-build-tools/pull/1120) should resolve this issue.

It will allow you to categorically suppress all TSDoc errors for code comment syntax, while still showing errors pertaining to API Extractor's analysis.

**Comment by octogonz** [comment]
Closing this issue, since version 7.0.22 provides a way to suppress errors.  We could make the experience even better in the future (e.g. a "lax mode"), but we should track that as a separate issue.
