### ISSUE TITLE
[rush] rush publish should take in optional --access flag (passthrough to npm publish)

### ISSUE THREAD

**Issue by cliffkoh** [Microsoft/web-build-tools#984]
`rush publish` should support `--access` argument to pass through to NPM.

I will be willing to submit a PR to add this. 
See https://github.com/OfficeDev/office-ui-fabric-react/issues/7253 for more context.

**Comment by pgonzal** [comment]
Are you sure this should be a command-line flag? I thought public/private publishing was a somewhat constant choice for a package. If so, maybe this should be a per-project or per-version-policy setting in a config file?

**Comment by cliffkoh** [comment]
Hi @KevinTCoughlin, any progress on this?

**Comment by KevinTCoughlin** [comment]
> 
> 
> Hi @KevinTCoughlin, any progress on this?

I have the sledgehammer approach to this problem using config JSON in a branch, but I'm not thrilled with it.

https://github.com/Microsoft/web-build-tools/compare/master...KevinTCoughlin:keco/support-access-cli-arg

The above will uniformly apply the flag across _all_ packages published which should resolve OfficeDev/office-ui-fabric-react#7253.

Do we see value in setting this flag at the version policy / publish group level?

If done per publish group, OUFR would need to enforce that new packages are added to that version policy. Otherwise we'd face the same problem.

Judging from documentation, both NPM and Yarn support the `--access` flag out of Rush's supported package managers.

- https://docs.npmjs.com/misc/config#access
- https://yarnpkg.com/en/docs/cli/publish#toc-yarn-publish-access

**Comment by cliffkoh** [comment]
In OUFR's case, all new packages are already in a lockedMajor version policy (although the new package template comments it out when `shouldPublish=false`). When shouldPublish is flipped to true, we expect that the `lockedMajor` version policy is uncommented. 

So to your question, that version policy requirement should be fine. 

But as to whether this approach you've is something that we should check in, I will defer to @pgonzal :) (I am personally fine with it but I suspect the much more complicated "at the version policy level" is the right answer even though it isn't required by OUFR).

**Comment by cliffkoh** [comment]
@KevinTCoughlin since version policy is kind of an arcane thing, would it be simpler/more straightforward/more intuitive to implement this at a per-package level?

**Comment by KevinTCoughlin** [comment]
> 
> 
> @KevinTCoughlin since version policy is kind of an arcane thing, would it be simpler/more straightforward/more intuitive to implement this at a per-package level?

Yea, I think so. We would need a mechanism to enforce a default value though, otherwise the OUFR problem may still occur.

**Comment by cliffkoh** [comment]
Good point - your work may still be really helpful for the purposes of establishing a default :+1:
