### ISSUE TITLE
[api-extractor] Extract ApiModel into a separate package "api-extractor-model"

### ISSUE THREAD

**Issue by octogonz** [Microsoft/web-build-tools#988]
@nvh [asked](https://gitter.im/web-build-tools/web-build-tools?at=5c097554aa741e1a65edfb41):

> Is there any reason why ApiPackage, ApiModel and the likes should theoretically not work inside a browser environment?

> We have a system that does static site generation based on React components, so they are preprocessed and the api.json will not end up on the client or in the js code, but it does require use to use the ApiModel in a web-context instead of node
> 
> So in theory this could server side rendering could be done in a node-environment, but because some components are dynamic and will end up in a script that runs client-side, the built system is all run without node

 I'm thinking we could basically take everything under the api-extractor/src/api folder (excluding Extractor.ts and IExtractorConfig.ts and IndentedWriter.ts) and extract that into a separate NPM package called **\@microsoft/api-extractor-model**. This subset will have no dependency on the TypeScript compiler, and contain only the stuff a documentation tool would need to read the .api.json data files.
This subset would depend on the **\@microsoft/tsdoc** library. But it would not depend on NodeJS, and should be able to execute in a browser.

**Comment by nvh** [comment]
What's the status on this, and is there anything I can do to help out?

**Comment by pgonzal** [comment]
I'll see if I can create a PR this week, and then you can tell me if it has the right stuff you need. We already got the new NPM package approved a while ago, so this should be pretty fast to turn around.

**Comment by nvh** [comment]
After doing some more research into our usecase it turns out we might not need this after all. I still think it would be a nice abstraction and would be happy to test it out with our setup, but wanted to let you know that there's less urgency for this from our side

**Comment by pgonzal** [comment]
FYI @natalieethell was recently working on something for **office-ui-fabric-react** that seems similar to what you described. They have a web application that displays TSDoc content. Initially they considered loading the **.api.json** files directly into the application as an asset, but they ultimately decided to create a small build task that uses the **@microsoft/api-extractor** library to load up the **.api.json** file and then writes it out as **.page.json** files, which are a preprocessed format that is much more compact and tailored for the specific needs of their application.

Nonetheless I'm going to keep this issue open, since separating the model from the extractor layer seems like a good idea in general.

**Comment by nvh** [comment]
This is exactly the road we decided to go down to. I'm not sure if your work or ours will have the same goals or strategy, @natalieethell, but it might make sense to share thoughts at some point. Feel free to contact me through niels@framer.com if you're interested.

**Comment by octogonz** [comment]
BTW here's a PR that creates the new `@microsoft/api-extractor-model` package: https://github.com/Microsoft/web-build-tools/pull/1140
